package ru.stqa.webtests;// Generated by Selenium IDE


import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class SearchtestTest {
  private WebDriver driver;
   //private Map<String, Object> vars;
   //JavascriptExecutor js;

  @BeforeTest

  public void setUp() {
    System.setProperty("webdriver.chrome.driver","D:\\DEV\\chromeWebDrv105\\chromedriver.exe");
    driver = new ChromeDriver();

     //js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  }

  @AfterTest
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchtest() throws InterruptedException {
    driver.get("https://www.selenium.dev/selenium/web/web-form.html");
    driver.manage().window().setSize(new Dimension(1440, 1040));
        String title = driver.getTitle();
    driver.findElement(By.name("my-text")).click();
    driver.findElement(By.name("my-text")).sendKeys("hooy pizda");
   // driver.findElement(By.name("btnK")).click();

    Thread.sleep(8000);
    System.out.println("Time test method two");

  }

}
